openapi: 3.0.3
info:
  title: SemiconductorLab Platform API
  version: 1.0.0
  description: |
    Enterprise-grade semiconductor characterization platform API.

    ## Features
    - Instrument management and control
    - Experiment orchestration
    - Real-time data acquisition
    - Advanced analysis (SPC, ML, VM)
    - Reporting and compliance

    ## Authentication
    Uses OAuth2/OIDC with JWT bearer tokens.

  contact:
    name: Platform Team
    email: platform@semiconductorlab.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:8000/api/v1
    description: Local development
  - url: https://staging-api.semiconductorlab.com/api/v1
    description: Staging environment
  - url: https://api.semiconductorlab.com/api/v1
    description: Production environment

tags:
  - name: auth
    description: Authentication and authorization
  - name: users
    description: User management
  - name: organizations
    description: Organization management
  - name: projects
    description: Project management
  - name: instruments
    description: Instrument registry and control
  - name: calibrations
    description: Calibration tracking
  - name: samples
    description: Sample/wafer/die management
  - name: methods
    description: Characterization methods
  - name: runs
    description: Experiment runs
  - name: results
    description: Analysis results
  - name: spc
    description: Statistical Process Control
  - name: ml
    description: Machine Learning / Virtual Metrology
  - name: reports
    description: Report generation
  - name: eln
    description: Electronic Lab Notebook

security:
  - BearerAuth: []

# [Paths and components continue...]

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          example: invalid_request
        message:
          type: string
          example: The request parameters are invalid
        details:
          type: object

    TokenResponse:
      type: object
      required:
        - access_token
        - token_type
        - expires_in
      properties:
        access_token:
          type: string
        token_type:
          type: string
          example: Bearer
        expires_in:
          type: integer
          example: 3600
        refresh_token:
          type: string

    User:
      type: object
      required:
        - id
        - email
        - first_name
        - last_name
        - role
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        first_name:
          type: string
        last_name:
          type: string
        role:
          type: string
          enum: [admin, pi, engineer, technician, viewer]
        organization_id:
          type: string
          format: uuid
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

  parameters:
    PageParam:
      name: page
      in: query
      schema:
        type: integer
        minimum: 1
        default: 1

    PageSizeParam:
      name: page_size
      in: query
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20

  responses:
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
